
spring.application.name=SpringAura

# --- DESACTIVAMOS MYSQL PARA QUE LOS TESTS USEN H2 ---
# spring.datasource.url=jdbc:mysql://localhost:3306/aura_reviews?createDatabaseIfNotExist=true
# spring.datasource.username=root
# spring.datasource.password=1234

# spring.jpa.hibernate.ddl-auto=update

# Cambia 'update' por 'create-drop'
# spring.jpa.hibernate.ddl-auto=create-dro

# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Opcional: si queremos ver SQL, descomentar esto:
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
server.port=8082






