name: Publicación de Releases Oficiales

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generar .war sin tests
        run: mvn -B clean package -DskipTests

      - name: Crear Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Subir .war a la Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.war
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
