name: Escaneo de Vulnerabilidades OWASP

on:
  push:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Ejecutar Dependency-Check
        run: mvn -B org.owasp:dependency-check-maven:check

      - name: Subir informe OWASP
        uses: actions/upload-artifact@v4
        with:
          name: reporte-owasp
          path: target/dependency-check-report.html
