name: Vigilante Universal

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compilar con Maven
        run: mvn -B package

      - name: Notificador de estado
        run: |
          echo "----------------------------------------"
          echo "DESPLIEGUE COMPLETADO CORRECTAMENTE"
          echo "Autor del despliegue: ${{ github.actor }}"
          echo "Fecha: $(date)"
          echo "Mensaje: El despliegue se realizó con éxito."
          echo "----------------------------------------"
