name: Publicar Javadoc en GitHub Pages

on:
  push:
    branches:
      - feature-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generar Javadoc
        run: mvn -B javadoc:javadoc

      - name: Deploy a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: target/site/apidocs
